ananthakumaran/tide

README.md, tide.el
- Use bound-and-true-p
- Refactoring sample code block
=> Refactoring

tide.el
This contains the unrelated changes separated out of pull request #21.
=> Small miscellaneous changes

tide.el
=> Fix completion at beginning of buffer or its restriction

tide.el
Note that you need to add `(add-to-list 'auto-mode-alist '("\\.js$" . typescript-mode))` in your `.emacs`.
=> Enable tsserver's javascript (and tsx/jsx) support

tide.el
Add a minor mode for automatically highlighting occurences of an ID.
=> add tide-hl-identifier-mode

tide.el
Fixes https://github.com/ananthakumaran/tide/issues/68.
=> expose ignore-case company mode option

tide.el
This PR provides a better UI and UX for renaming a symbol.
* The mini-buffer text has a colon: to separate input from prompt.
* The mini-buffer text-box provides a default-value.
=> Improve experience of symbol-renaming.

README.md, tide.el
This closes https://github.com/ananthakumaran/tide/issues/116.
=> Add support for code-fixes.

tide.el
This closes https://github.com/ananthakumaran/tide/issues/107.
=> Implement support for basic type-search with navigation.

tide.el
This closes https://github.com/ananthakumaran/tide/issues/97.
The reponse from "Jump to implementation" is not as rich as I'd like it to be: [We only get filename and position back, and no class-names](https://github.com/Microsoft/TypeScript/blob/master/src/server/protocol.ts#L585-L590).
It's not entirely uncommon to have several implementations of the same interface in the same file, so for that reason I decided that showing file-name alone was probably not specific enough to get a "unique" index we could use to look up the user's selection.
Let me know if you can think of a better way to solve this :)
Thanks to @AndyMoreland for giving me the push to provide all these patches :)
=> Implement support for "jump to implementation".

tide.el
Hi, adding capability to complete strings.
=> + completions for strings

tide-lv.el, tide.el
falls back to the old model when there are more than 7 choices.
screenshots
=> use magit/hydra like popup for choice

tide.el
* Don't flatten the tree by default
* during flatten step, prefix the parent node's text before the child
node's text
fixes #5 #145
=> cleanup imenu

tide.el
if the cursor inside the *-errors* buffer is moved while the insert is
going on, text gets inserted in the wrong order.
=> make sure texts are inserted in the end

tide.el
=> ignore empty response incase of eldoc

tide-tests.el, tide.el
=> add support for jsdoc tags

README.md, tide.el
https://github.com/Microsoft/TypeScript/pull/16960
=> add support for extract method

tide.el
=> handle file rename

tide.el
This PR contains the changes proposed and implemented by @leo-shopify in #193, but includes additional patches, and as such supersedes it.
It further includes changes proposed in the discussion in #190.
Maybe I'm overly optimistic, but I'd like to think that the *specification* for how this should work is mostly settled after 2 looong threads in separate issues.
Therefore at this point, I hope review and comments should be able to focus on the code and implementation.
That said... Testing, review and comments is very much welcome :)
CC: @ananthakumaran @lddubeau @leo-shopify @asmundg @MarcusRiemer
=> Improved algorithm for finding a good tsserver

tide.el
**Testing notes**
this feature works only with tsserver >= 2.6.1, but should not break anything in old tsserver
=> add support for auto-import on code completion

README.md, tide.el
=> add support for jsdoc template command

README.md, tide.el
=> enable auto import suggestion by default

Makefile, test/base.json, test/loop.json, test/tsconfig.json, tide-tests.el, tide.el
fixes #225 
@sbuzonas please test this branch
=> respect extends in tsconfig.json file

tide.el
add support for the two cases mentioned in [1](https://code.visualstudio.com/updates/v1_20#_bracket-property-suggestions) and [2](https://code.visualstudio.com/updates/v1_20#_automatic-member-property-suggestions)
=> add support for completion with inserText

tide.el
fixes #226 
@it6 @mbenedettini can you guys test this branch and see if it improves the situation.
=> improve import autocomplete

tide.el
fixes #283 
Suggestions from tsserver are shown as flycheck **info** messages. This fix also enables other types of codefixes like convert to an async function, value is never read etc.
=> fetch suggestions

tide.el
=> Fix minor typo

.travis.yml
We should also test on Emacs 26.1. 
I'm putting this on a PR so that the tests are run and I can check whether there's any change that must be made in the code. I'll merge once everything is clean.
=> Include Emacs 26.1 in the tests.

.travis.yml, tide.el
Make sure only one of them is enabled based on the file extension.
closes #251
=> Enable either jsx or tsx flycheck checker

tide.el
Some random minor improvements, split into different commits in case some are not wanted.
=> Minor improvements

tide.el
Tiny fix for compile on save in recent tsc versions
=> Update parsing for tsconfig option "compileOnSave"

tide-tests.el, tide.el
Cleaning up some more code (including chopping huge lines); and get rid of all compiler warnings.
See commit messages for details.
=> Some fixes

tide.el
=> Add some grep-like bindings

tide.el
* Abstract moving forward/backward in a separate function, which also
fixes a bug when moving back from the middle of an identifier.
* Make `tide-next-reference-function` use `set-window-point` when a
window is shown, otherwise things get confusing since the point can
reset itself back to the one displayed in a window.  (When navigating
to a new buffer, the reference buffer can be hidden, and at that time
the value of `(point)` reverts to wherever the visible point was.)
* Add `tide-cycle-next-reference` that cycles back at the buffer end(s).
Bind it to `TAB`.
=> Improve reference navigation functions

tide.el
As mentioned in #278 (which this supersedes).
* Rewrite much of `tide-insert-references`, so the code is simpler and
the rendering is better.  Use `line-prefix` to display line numbers,
add `tide-line-reference` on the whole line to make it easy to jump
from anywhere on a line.
* Add `tide-goto-line-reference` that uses the above to jump to the
referenced file at the location that we were at.  Use it as a binding
for `RET`, leaving `tide-goto-reference` the same for mouse clicks.
=> Improve reference buffer

README.md
@josteink here you go (fixes #381) :)
=> Add instructions for usage with Deno projects

tide.el
=> add strikethrough property for deprecated candidate

tide.el
refer https://github.com/company-mode/company-mode/pull/1083
=> add support for company mode icons

tide.el
Project error needs to be requested in the context of a project
file. The initial buffer file name from which the command was issued
is captured as origin and later used when refresh is requested.
fixes #439
=> add refresh support to project error buffer

tide.el
1. Setup of eldoc is slightly different: add-hook to eldoc-documentation-functions instead of making a local variable.
2. eldoc-message is now deprecated, and the function gets a callback to call instead.
This lets newer eldoc-based frontends work, like eldoc-overlay.
I don't know how widely supported eldoc 1.1.0 is, or how to tell. It ships with emacs 28. If it's not widely installed, then this PR is not a good idea.
=> Update to eldoc 1.1.0
