tide.el
string-blank-p was introduced at Emacs 24.4. And subr-x.el must be loaded.
=> Fix for older Emacs

tide.el
As of Flycheck version 27 (on melpa and melpa-stable now), TSLint checker is built-in. This checker conflicts with tide-mode somehow, only errors from `typescript-tide` checker are shown in errors list. Only solution that I found working is to run `typescript-tslint` checker after `typescript-tide` checker.
=> Fixed conflict with typescript-tslint checker from Flycheck 27

tide-pkg.el
Because package information is also declared at package header in tide.el
and pkg file content does not match with package header in tide.el.
This is confused.
=> Remove pkg file

tide.el
This package already uses some cl-lib functions/macros but cl-lib is not
loaded. And it is not good to use both cl.el and cl-lib.el.
=> Use cl-lib functions/macros instead cl.el

tide.el
If there is a single usage of a symbol, then tide-references jumps directly to it instead of creating a \*tide-references\* buffer. Then tide-jump-to-definition jumps back to the definition. For example:
```ts
/*1*/function usedOnce() { }
/*2*/usedOnce();
```
When the cursor is at (1), `tide-references` jumps to (2). When the cursor is at (2), `tide-jump-to-definition` jumps to (1). Otherwise (in case there is more than one usage or more than one declaration), \*tide-references\* is created normally.
Note that this requires TypeScript 2.0, which adds isDefinition to ReferenceEntry to support this feature.
Fixes #55
=> Make `tide-references` jump directly to a single reference

tide.el
After looking into this, I found out that setting text-properties in a `compilation-mode` buffer is troublesome. Basically they will get constantly wiped, as `compilation-mode` tries to update its own properties (and handle the fact that it can be used in a comint).
Working around this would require quite some cumbersome hacks, and possibly have to rely on Emacs' current implementation of `compilation-mode`. Leaving aside the stability and compatibility issues that would entail, it also wouldn't really create any nicer code than what we already have.
And since you insisted on the formatting to stay pretty much exactly as it already is... I decided to try another approach which did not rely on `compilation-mode` directly: I looked into what `next-error` and `previous-error` does and how …
=> Make references support next-error and previous-error.

tide.el
With current implementation `tide-documentation-at-point` returns a buffer where you can edit it's content and you have to manually kill the buffer when you're done working with it.
This patch makes the documentation-buffer read-only, and makes it easily closable according to existing Emacs-conventions by simply pressing "q".
=> Make doc-view mode read-only and easily closed.

tide.el
Currently the current code *may* produce something like the following
in the minibuffer:
````
Rename "d:/repo/src/ui/viewBase".ViewBase to: "d:/repo/src/ui/viewBase".ViewBase
````
With this commit, we get the symbol-name only, as expected:
````
Rename ViewBase to: ViewBase
````
=> Rename: prettify symbol-name presented when doing rename-refactoring

tide.el
This also helps improve the usability of tide and makes it more consistent with how other built-in and third-part Emacs-modules operate.
=> Make references in tide-references mouse-clickable.

example/test.ts, tide.el
Otherwise, company-mode will throw an error when
company-tooltip-align-annotations is non-nil. Also
added a line in example/test.ts that repro-ed this,
because the Object type had a multi-line annotation.
=> Ensure annotations are only one line.

tide.el
M-x tide-project-errors fails to run on my Emacs 24.5.1 with errors that copy-list and incf aren't available.
=> tide-display-erros: Use cl-copy-list / cl-incf

tide.el
After doing (better) testing of `tide-nav`, I discovered the following:
* my hacky "disable helm" workaround doesn't actually seem to work reliably. I must have messed something up during testing.
* Getting "something" which works in helm wasn't that hard.
This patch lets you type something, then press `<TAB>`(just as a regular completing-read would have you do) and then you get a helm-popup with the candidates, ready for selection. Much better than it used to be.
To avoid more errors in this department I've tested the following configurations:
* helm
* ido
* ivy
* none of the above
From what I can tell it all works as expected now.
=> Fix tide-nav for helm.

tide.el
As discussed in issue #122, Emacs actually never expects anything except `\n` to be inserted in a buffer for newlines, no matter how newlines is actually represented in that file.
Us inserting `^M` characters returned from `tsserver` is thus not us doing things properly nor preserving correctness. On the contrary it's our code being a source of (quite terrible!) bugs.
This PR fixes this and closes #122.
=> Fix newline issues with code-edits.

tide.el
The previous version of this function would always convert the location to point before doing the comparison. When the location was to a point that is greater than the size of the current buffer, it would cause a fatal error. The new version will do the conversion of location to point only if the current buffer's file name and the other file name are a match.
=> Don't convert location to point unnecessarily.

tide.el
This removes another sync call and will probably fix #113 and could help with #133
\cc @josteink
=> use async callbacks for eldoc

tide.el
`file-relative-name` returns relative path for `tsmft.json` in the current directory, often producing something like `src/component/tsfmt.json`
`expand-file-name` provides the intended behaviour.
=> Bug Fix: use expand file name to get full tsfmt.json path

tide.el
This fixes a hang that occurs if a message >1k is sent to tsserver on macOS (and
perhaps other OSes, the author has only tested on macOS).
Fixes #144
=> Use a pipe to connect to process

tide-tests.el, tide.el
This PR solves two issues with the code completion.
When completing properties and methods of an object, Tide would list all possible symbols as candidates.
_Edit_: I've just realized this behavior can be reproduced only for JavaScript files, not if I put the same code into a `.ts` file. 🤷‍♂️ 
Before the patch:
With the patch – we display only the properties and methods of the object at point:
When completing a variable, Tide provides all possible symbols in the scope, sorted alphabetically.
It would be nicer to sort the candidates by scope. First, show the function parameters and locally defined variables, then local functions and outer variables, and finally library functions (i.e. declarations from typings).
Before:
After:
---
What do you think? I would be glad to incorporate any …
=> Filter & sort completion candidates by kind

tide-tests.el, tide.el
This PR resolves #149 by removing the additional client-side filtering of code completion candidates.
=> fix: removed filtering of member completions (see #149)

tide.el
Apparently, `definition` tsserver requests can sometimes return a success code but with a body that is an empty array. I was seeing this in my tsserver log when using `tide-jump-to-definition` in some code:
```
Info 62   request: {"command":"definition","seq":"5886","arguments":{"file":"<filename redacted>","line":42,"offset":45}}
Perf 63   5886::definition: elapsed time (in milliseconds) 3.9150
Info 64   response: {"seq":0,"type":"response","command":"definition","request_seq":"5886","success":true,"body":[]}
```
Which was causing tide to throw these error messages:
```
error in process filter: Wrong type argument: stringp, nil
```
This PR effectively just silences that error--I don't know if there's anything better to do in that situation, though I might look and see why tsserver can't …
=> Don't error out on an empty definition response

tide.el
This addresses https://github.com/ananthakumaran/tide/issues/169.
cc @raxod502: Could you test and see if this change works for you?
=> Fix problem with incorrect lineshift-format in documentation-buffers

tide.el
[rjsx-mode](https://github.com/felipeochoa/rjsx-mode) claims to be a better version of `js2-jsx-mode`. Better or not, Tide seems to work without a problem in this mode, so let's be friends with it.
=> Add rjsx-mode support

tide.el
Some users might choose to disable eldoc and only show type information on demand. Type information can also take up multiple lines and might not fit within the echo area. In such cases, the documentation window can be useful, but currently, it isn't shown unless documentation is actually present. I added an option to show the documentation window even if only type information is available.
=> added option to always show documentation window

README.md, tide.el
introduced by https://github.com/Microsoft/TypeScript/pull/15569
=> add support for refactor command

tide.el
```elisp
;; eslint-fix-file function will be called for each buffer that has changed
(add-hook 'tide-post-code-edit-hook #'eslint-fix-file)
```
fixes #168
=> add post code edit hook

tide.el
`tide-command:openfile` assumes `buffer-file-name` is a string when evaluating its body.
This is not the case when exporting javascript org-mode code blocks to html, for example.
Checking that `buffer-file-name` is a string prevents evaluation errors and returning `nil` is enough for the org-mode export case to work.
This was the top of the stack trace before the change:
```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
file-name-nondirectory(nil)
file-name-extension(nil)
tide-command:openfile()
tide-configure-buffer()
tide-setup()
setup-tide-mode()
js2-mode()
funcall(js2-mode)
org-html-fontify-code("" "js")
```
=> ensure `buffer-file-name` is a string

tide.el
see https://github.com/Microsoft/TypeScript/pull/18351 for details. This is backward compatible if renameLocation is not present it won't do anything. To test it locally, you need to use `release-2.5` branch of `TypeScript`
=> trigger rename command after refactor

tide.el
Closes #216 
I took out the read-only declaration, the `quit-window` binding, and the `use-local-map` call. The first two are definitely taken care of by special-mode; the last one I think all minor modes do. I tested the changes on 25.2 and everything worked the same
=> Derive project-errors and references modes from special-mode

tide-tests.el, tide.el
Fixes #214 by adding a custom variable. Ideally the sorting would just be removed, but some people may prefer to have it on.
Note that the variable defaults to `nil`, however.
=> defcustom to turn off sorting completions by kind

tide.el
Fixes #217
I'm not familiar with the `tsserver` methods, but it seems like the navtree hierarchy always has a single element as its root.
=> Skip first layer when building a hierarchical imenu index

example/all.d.ts, example/literate.org, example/test.ts, example/tsconfig.json, example/vueComponent.vue, tide.el
This allows tide to be used in e.g. template files. The only caveat is that the file has to be manually added to tsconfig.json, as the globs in the include array ignore non-typescript files (see https://github.com/Microsoft/TypeScript/issues/8328). Otherwise the file will be added to an inferred project with default compiler settings. This fixes #198.
=> Add support for indirect buffers

tide.el
I wasn't able to use `tide-fix` with latest master, this PR fixes it but I have no knowledge in eslip/lisp so I have no idea what I'm doing 🤔
=> Fix tide-command:getCodeFixes failing with getting file name

README.md, tide.el
Related to https://github.com/Microsoft/TypeScript/pull/20338. Need typescript@next for testing.
=> add support for fix all in file & project-info

tide.el
fixes #236 
@bdowning I am not able to reproduce it locally with version `2.8.0-dev.20180127`. But I guess this should fix/workaround the bug. Could it test it out?
=> verify filename before applying highlights

test/tsconfig-no-extension.json, tide-tests.el, tide.el
The `"extends"` field in `tsconfig.json` files may specify a file name
with or without extension. E.g. if the file `"./base.json"` exists then
a `tsconfig.json` with:
```
"extends": "./base"
```
is equivalent to a tsconfig.json with:
```
"extends": "./base.json"
```
=> Support tsconfig with "extends" field without extension.

README.md, tide.el
this command is only available on Typescript master branch
=> add support for organizeImports command

ISSUE_TEMPLATE.md
This is the PR for the issue template i mentioned in #246.
There are two areas I'm still unsure about:
1. There's a step in the checklist asking to reproduce the problem with the latest version of tide. I'm not sure what specific version we should consider to be "latest" for our purposes here. I know some projects ask submitters to test against the master branch, which in some cases I consider to be an excessive request because checking out the project's master branch and building it to check whether the issue still happens there is a major enterprise. Ever since I've started contributing to tide I've been running tide from the master branch anyway so I've lost track of how often releases are pushed to the package repository (or repositories) and therefore I don't have a clear idea of the …
=> Guidance for filing issues.

tide-tests.el, tide.el
@lddubeau What do you think about this approach? Using `&optional` and `&rest` in the same function seems like a tricky thing, I am not entirely sure if this will introduce any other issues. 
P.S. Accidentally pushed to master(reverted now)
=> fix invalid tide-on-response-success calls

README.md
I left out the bits for configuring company/flycheck since with use-package you'd probably have that setup already.
Fixes #227
=> Add setup instructions for use-package

README.md
Even with the deferred loading, the original use-package example would enable `tide` for _every_ buffer, along with the hook for formatting before save. This would result in non-JS/TS files being corrupted when saving changes, for example:
Before saving the file:
(add-to-list 'auto-mode-alist '("\\.jsx\\'" . web-mode))
After saving the file:
(add - to - list 'auto - mode - alist '(  "\\.jsx\\'" . web - mode ) )
It might not happen all the time (possibly it only happens in conjunction with other settings, as it never occurred when first trying it out). It took a few days to realise my example here was destroying my init.el. :)
=> Fix use-package config to only load Tide for TS/JS

tide-tests.el, tide.el
This is not complete yet because I've not added a test for it to the test suite, but I've been sitting on this since last October. It is high time it be integrated *somewhere*.
This essentially adds a function that allows for automatically turning off `tslint` warnings. The gory details are in the docstring for the new function, but here is an example:
```
if (something.foo("blah"))
```
If you have 5 `tslint` rules giving you warnings at `foo` and you move your point there and issue `tide-add-tslint-disable-next-line` then your code will become:
```
// tslint:disable-next-line:[rule1] [rule2] [rule3] [rule4] [rule5]
if (something.foo("blah"))
```
I feel the function I'm adding here is more `tide`-y than `typescript-mode`-y but maybe there's a good argument to be made that it belongs to …
=> Add tide-add-tslint-disable-next-line

tide.el
Based on the discussion in #265, I made a simple customize entry for tide-nav's item filtering.
It's not fancy right now, for two reasons:
1. I'm not confident with defcustom (or emacs develoment in general), so I tried the simplest thing that would work.
2. I think that All and Types are the only two choices that make sense, so something fancier like a big checklist would only confuse people. In addition, implementing All by checking the entire checklist would also be slow, since it would be `member` of a medium-ish list filtered over a large list.
The biggest obstacle, however, is (1), so please do suggest improvements if you see them.
=> Make tide-nav filter customizable

README.md, tide.el
This [refactor](https://code.visualstudio.com/updates/v1_24#_move-to-new-file-refactoring) is only enabled if `allowTextChangesInNewFiles` flag is
set on the configure request. Handle code edits for non existent file.
=> support move-to-file refactor

.travis.yml, tide-tests.el, tide.el
Taking a page out of [magit](https://github.com/magit/magit), this PR adds code so that tide formally checks whether the Emacs it is running on is at least as new as the oldest version supported.
When the check fails, the user gets a warning. This is what magit does. I've not spent any time figuring out the pros and cons of showing a warning like magit does vs slamming the brakes with a hard failure.
This also removes 24.3 from testing, as 24.4 is the oldest version supported.
=> Formalize the range of Emacs versions supported

README.md, test/trivial.ts, tide-tests.el, tide.el
I'm opening a PR so that this can be discussed before it is merged. Or so that it can be objected to, if there are objections.
The explosion of `tsserver` processes has been a bit of an issue for me. I can do `ps` at the command line but that's rather limited in usefulness. I can also use `M-x list-processes` but it shows things I don't care about and conversely does not readily provide information I care about when I'm inspecting `tsserver` processes. So I've worked on a `tide-list-servers` command which can help inspect the instance that tide has started. I've derived it from how `list-processes` does its job.
Things that can be done with it:
1. See the servers running.
2. Kill a server by hitting `d` in the `*Tide Server List*` buffer.
3. Verify the configuration of a server by going …
=> WIP: server management

README.md, tide.el
see #275 for context
I initially thought of adding the extra information after the current normal message as @josteink suggested.
Some drawbacks of that approach are
1) we won't be able to navigate to the location 
2) minibuffer height is usually fixed, anything more than 4 lines is usually a problem
An arrow is shown in the end if there are any related information available. User can then run `M-x tide-error-at-point`, which will bring up a buffer. Similar to `tide-documentation-at-point`. The link to the file position is clickable.
Flycheck has `flycheck-explain-error-at-point` command, I attempted to integrate with it, but unfortunately it doesn't allow clickable link. It uses `princ` internally which ignores all the text properties.
=> add command to show detailed error at point

tide.el
Either on Emacs 27 or macOS, cpu is nil and `isnan` throws when you give it nil. Either way, this fixes it for me.
=> Fix tide-list-servers when cpu is nil

README.md, test/base.json, test/loop.json, test/tsconfig-no-extension.json, test/tsconfig.json, tide-tests.el, tide.el
Note: This breaks backward compatibility as --showConfig is only introduced in 3.2. But given that the config is only used by a small feature and maintaining backward compatibility will make the code too complicated, I am leaning towards only supporting 3.2 for this feature 
fixes #310 @zhenwenc please help with testing
=> use tsc --showConfig to read config

test/highlight.ts, tide-tests.el, tide.el
I'm proposing this instead of #324 
The problem with `tide--hl-highlight` being slow is that `tide-location-to-point` is extremely slow because with every invocation it goes back to `point-min` and moves forward to find the point to return. I've briefly investigated whether it was possible to *only* replace the guts of `tide-location-to-point` with something speedier but I've not found a way to do this.
What I ended up with is a specialized loop that remembers from iteration to iteration which line it is at in the buffer so it does not keep jumping around the buffer. With this modification, when I use `benchmark-elapse` (from `benchmark.el`) to time `tide--hl-highlight` I get a run time of 0.0034 down from about 1.3 prior to the modification. This is using @sandersn's test case: the …
=> Improve the speed of tide--hl-highlight.

test/highlight-tabs.ts, tide-tests.el, tide.el
Fixes #337
As the documentation of `move-to-column` states, it calculates the width of each character. A tab counts 8 character wide even though it is only one character in the source code, etc. Hilarity ensues. Use `forward-char` instead.
@zanemayo please try it out on substantial files.
=> Fix highlighting when the file contains tabs.

tide.el
Make `tide-file` inherit directly from `font-lock-type-face` instead of
`dired-header`, since that doesn't exist until `dired` is used (so
opening the references before dired gets no highlights).
=> Better `tide-file` face definition

tide.el
Occasionally tide won't be able to find a definition. In cases like this it'd be nice to fallback to another jump method (e.g. [dumb-jump](https://github.com/jacktasia/dumb-jump)).
Here's an approach that I'm finding useful:
```elisp
(use-package tide
:ensure t
:after (typescript-mode company)
:config
(setq tide-jump-to-fallback 'dumb-jump-go)
:hook ((typescript-mode . tide-setup)
(typescript-mode . tide-hl-identifier-mode)
(before-save . tide-format-before-save)))
```
=> Add optional tide-jump-to-fallback

tide.el
There is a general tendency to accumulate many servers since they're
never removed (actually, more than just the servers -- the whole project
resources are kept, but the server is the main problem wrt resources).
This is also mentioned in #256.
So I implemented a function that scans all buffers and cleanup all
projects that have no live buffers.  It looks to me like a good idea to
do this, since you can just kill old buffers to reduce resource
usage.  (And killing old buffers is more obvious than explicitly
openning the server list to kill old ones, especially since there's no
way to tell if a server is used by some buffer or not.)
(I added this function onto `kill-buffer-hook`, but if that's too
extreme, then a more mild option is to not do that and just let people
add it themselves.)
=> Project cleanup when buffers are killed

tide.el
Need to write the whole file, otherwise things won't work when viewing a
narrowed part of the buffer.
=> Fix writing temp file for a buffer

tide.el
I've seen many tmp files left.  Looking at the code, it seems to me like
a reasonable thing to get rid of them when a file is saved.  I did this
via adding `tide-remove-tmp-file` on `after-save-hook`.
=> More temp file cleanups

test/trivial2.ts, tide-tests.el, tide.el
This is the companion WIP to issue #294 
I've been using this for a few weeks now without running into actual issues (commit dates are deceptive: I used it before the code was committed) so I figure I should put it up for public view.
Going into a buffer that does not have `tsserver` started causes some things to not work but *that's expected*. When I finally start a `tsserver` manually it works just as well as if the server had been started automatically.
=> allow not starting tsserver immediately when starting tide

tide.el
An error occurs if the file name has no extension.
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
upcase(nil)
(let ((extension (upcase (file-name-extension (tide-buffer-file-name))))) (if (member extension (quote ("TS" "JS" "TSX" "JSX"))) (progn (list (quote :scriptKindName) extension))))
(append (list (quote :file) (tide-buffer-file-name)) (let ((extension (upcase (file-name-extension (tide-buffer-file-name))))) (if (member extension (quote ("TS" "JS" "TSX" "JSX"))) (progn (list (quote :scriptKindName) extension)))))
(if tide-require-manual-setup (list (quote :file) (tide-buffer-file-name) (quote :scriptKindName) tide-default-mode (quote :fileContent) (buffer-string)) (append (list (quote :file) (tide-buffer-file-name)) (let ((extension (upcase …
```
=> Fix `upcase(nil)` error

README.md, test/test.json, tide-tests.el, tide.el
I took a stab at making tide use the native json parser when it is available. There is a new variable `tide-native-json-parsing` that controls which JSON parser is used. I am quite new to writing elisp so I am happy to have feedback on how to improve the code.
Closes #374
=> Use native JSON parsing when available

tide-tests.el
The first two arguments are symbols, not arbitrary forms.
=> Fix edebug specification for ‘with-spy’.

tide.el
In Emacs 28+, eldoc-display-message-p() has been refactored to
eldoc-display-message-no-interference-p().
tide-eledoc-display-message-p() uses eldoc-display-message-no-interference-p()
if available, and falls back to eldoc-display-message-p() if not.
See #390
=> Adding tide-eledoc-display-message-p()

tide.el
Should be tide-eldoc-display-message-p()
Sorry, I copy'n'pasted the function name with typo in my previous commit/pull request.
See #390
=> Fixing typo in tide-eledoc-display-message-p() name

tide.el
This removes the need to add the same plugin across all `tsconfig.json` files.
A Deno only developer could now add the following to their `init.el`:
```elisp
(setq-default tide-tsserver-flags '("--globalPlugins" "typescript-deno-plugin"
"--pluginProbeLocations" "~/.npm/lib/node_modules/typescript-deno-plugin/"))
```
=> Add support for passing custom tsserver flags

tide.el
tsserver used to? send code edits for the new file name. Looks like it
sends code edits for old file name now. If we get any edits for old
file, apply it before rename. Apply the rest of the code edits after rename.
fixes #406
=> fix code edit handling on tide-rename-file

tide.el
fixes #408:
If the new name of a buffer clashes with an opened buffer then
tide-rename-file stops and doesn't apply after-rename-edits.
Especially problematic because tide leaves buffers open as it applies
code edits.
=> Fix tide-rename-file bug on new buffer name;

README.md, tide.el
Useful for large TypeScript codebases which need to set max-old-space-size to a higher value.
I have a large codebase that doesn't compile with the default value (😭 ) so the tsserver process crashes from time to time. This PR allows passing custom flags to the node process to change `max-old-space-size` (or whatever other flag).
Would you consider merging this?
Btw, massive thanks for tide 🙏
=> Add tide-node-flags customizable variable

tide.el
tslint tool is [deprecated](https://github.com/palantir/tslint#tslint) and the temp files created by it doesn't
play nice with tsserver as well.
see #412 #333
=> remove tslint

.github/workflows/ci.yml, tide.el
This function is inspired by `tide-tslint-disable-next-line`.
See #308
=> Add tide-eslint-disable-next-line

tide.el
Loading `tide.el` has the side-effect of adding the completion backend to `company-backends` with no configuration option. The user may however not wish to use `company-tide`, or not have it as the first backend.
Other `company` packages do not mangle `company-backends`, instead documenting the code to add their backend, to allow the user to add the backends in their preferred order (examples: [1](https://github.com/krzysztof-magosa/company-ansible#how-to-configure-company), [2](https://github.com/randomphrase/company-c-headers/tree/5e676ab0c2f287c868b1e3931afd4c78895910cd#setup), [3](https://github.com/tigersoldier/company-lsp/tree/f921ffa0cdc542c21dc3dd85f2c93df4288e83bd#usage)). I therefore propose this change to follow this convention.
=> Leave company-backends for the user to setup

tide.el
This commit attempts to reduce the number of times
`after-change-functions` is called when edits are applied. Otherwise,
with large enough buffer and complex font locking rules, emacs could
get blocked for long time.
Ideally the start and end of the region that is being changed should
be supplied to the function, but I am not sure how it could be
calculated easily as each edit affects successive edits' region.
For now, I have settled on using the min max point of the buffer and
apply the optimization only if there are more than two edits.
see #427
=> Avoid triggering too many change hooks

README.md, tide.el
Adds a new custom variable `tide-save-buffer-after-code-edit` to configure auto-save behaviour when applying code edits.
The variable defaults to `t` so there is no impact to current users.
=> Configure auto save when applying code edits

tide-tests.el, tide.el
Emacs is rolling out a new timestamp format, to be used by time-handling functions such as `current-time` and `time-subtract`. Tide assumes timestamps are in the old `(HI LO US PS)` format, and attempts to extract a number of seconds by directly pulling out an element from this list with `cadr`.  In order to properly work with the changing timestamp format, we need to use Emacs' provided functions for handling timestamps, rather than poking at the internals directly.
=> Fix handling of timestamps in new `(TICKS . HZ)` format

README.md, tide-tests.el, tide.el
This PR removes hard dependency on `typescript-mode` and adds support to treesitter based `typescript-ts-mode` (it keeps support for `typescript-mode`)
`typescript-mode` has been used directly only for indentation and after changing calls from `typescript-indent-line` to `indent-according-to-mode` we can safely remove hard dependency and support treesitter based modes at the same time.
=> Treesitter support

tide.el
If multiple flycheck checkers are used, `tide-add-eslint-disable-next-line` will also disable errors and warnings from different checkers.
=> fix: only disable eslint errors in tide-add-eslint-disable-next-line

tide.el
This PR is a continuation of work done in https://github.com/ananthakumaran/tide/pull/456 
It checks if emacs version is less than 28.1 (where `eldoc` 1.1 got introduced) and uses the old mechanism in that case.
=> Update to eldoc 1.1.0 with support for emacs < 28.1

tide.el
Fixes https://github.com/ananthakumaran/tide/issues/463
=> Update tsx-tide checker modes

tide.el
At work some changes were made recently to the way module resolution works which broke auto importing in Tide. Other editors such as VSCode were not affected, so we compared the tsserver requests/responses between VSCode and Tide and noticed that `completionEntryDetails` was returning an empty body for Tide but not VSCode. The only difference between the two requests was that VSCode included the `data` property under `entryNames` (included in the response from the `completions` request), whereas Tide did not. Patching Tide to include `data` fixed the issue.
I'm not sure why after these tsconfig changes tsserver no longer can provide completion entry details without the extra data, but the change to support this is minimal so I thought I'd contribute it upstream in case others hit the same …
=> Include data in completionEntryDetails request
